### PR TITLE
removed unused code

### PR DESCRIPTION
**Pull request by irrationalRock**
removes change and test acc

### CODE REVIEW

**Comment by DavidFerri-PRJ** [comment]
You also need to remove the * link on the log in page

**Comment by irrationalRock** [comment]
@ What do you mean by the `* link`

**Comment by DavidFerri-PRJ** [comment]
On the Home/Login view, delete  <p class="text-right">@Html.ActionLink("*", "TestAcc", "Home")</p>

**Comment by irrationalRock** [comment]
thanks, I didn't see it on the page

**Pull request merged**
